Repository eProsima/Fast-DDS-Gen, pull requests merged in 2024-07, with the labels that each got.

#365 [21226] Improve CI workflows in master, and branching model refactor
  .github/actions/fetch-fastddsgen-repos/action.yml
  .github/workflows/config/build.meta
  .github/workflows/config/test.repos
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/reusable-ubuntu-ci.yaml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/ubuntu-ci.yaml
  .github/workflows/ubuntu-ci.yml
  RELEASE_SUPPORT.md
Labels: ci-pending

#371 [21226] Improve CI workflows in master, and branching model refactor
  .github/actions/fetch-fastddsgen-repos/action.yml
  .github/workflows/config/build.meta
  .github/workflows/config/test.repos
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/reusable-ubuntu-ci.yaml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/ubuntu-ci.yaml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
  RELEASE_SUPPORT.md
Labels: ready-to-merge

#372 [21267] Fix weekly CI cron expression
  .github/workflows/weekly-ubuntu-ci.yml
Labels: skip-ci

#376 [21310] Set 3.2.x (Fast DDS 2.13.x) as EOL
  .github/pull_request_template.md
  .github/workflows/nightly-ubuntu-ci.yml
  RELEASE_SUPPORT.md
Labels: skip-ci

#377 [21324] Adapt example generation to Fast DDS examples refactor
  src/main/java/com/eprosima/fastdds/fastddsgen.java
  src/main/java/com/eprosima/fastdds/idl/templates/DDSApplicationHeader.stg
  src/main/java/com/eprosima/fastdds/idl/templates/DDSApplicationSource.stg
  src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubMain.stg
  src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherHeader.stg
  src/main/java/com/eprosima/fastdds/idl/templates/DDSPublisherSource.stg
  src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberHeader.stg
  src/main/java/com/eprosima/fastdds/idl/templates/DDSSubscriberSource.stg
Labels: ready-to-merge

#375 [21351] Refactor `TopicDataType`
  src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeHeader.stg
  src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSource.stg
  src/main/java/com/eprosima/fastdds/idl/templates/DDSPubSubTypeSwigInterface.stg
  src/main/java/com/eprosima/fastdds/idl/templates/SerializationTestSource.stg
Labels: ready-to-merge

#378 [21325] Remove all code related to FAST CDR v1
  src/main/java/com/eprosima/fastcdr/idl/templates/TypesSwigInterface.stg
Labels: ci-pending

#384 [21226] Fix nightly job
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
Labels: skip-ci

#319 [20362] Changes for xtypes1.3 doc
  src/main/java/com/eprosima/fastdds/fastddsgen.java
Labels: skip-ci
